on:
  push:
    branches:
      - dev
jobs:
  build-angular:
    runs-on: ubuntu-latest
    container: node:18
    steps:
    - uses: actions/checkout@v2
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Install depedencies and build
      run: | 
        cd ./VaBucherFront
        npm install
        ng serve
  build-dotnet:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
    - uses: actions/checkout@v2
    - name: Restore .NET dependencies
      run: dotnet restore
    - name: Build .NET application
      run: dotnet build --configuration Release
    - name: Publish .NET application
      run: dotnet publish --configuration Release --output dist
