on:
  push:
    branches:
      - dev
jobs:
  build-angular:
    runs-on: ubuntu-latest
    container: node:18
    steps:
    - uses: actions/checkout@v2
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Install depedencies and build
      run: | 
        cd ./VaBucherFront
        npm install
        ng serve
