on:
  push:
    branches:
      - dev
jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build .NET application
      run: |
        cd ./VabucherBack
        dotnet restore
        dotnet build --configuration Release
      
  build-angular:
    runs-on: ubuntu-latest
    container: node:18
    steps:
    - uses: actions/checkout@v2
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Install depedencies and build
      run: | 
        cd ./VaBucherFront
        npm install
        ng build
     
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      run: |
        docker build -t docker.io/adamoccidevops/vabucherback:${{ github.sha }} ./VabucherBack
        docker build -t docker.io/adamoccidevops/vabucherfront:${{ github.sha }} ./VaBucherFront
        echo "Alternance2022" | docker login --username adamoccidevops --password-stdin
        docker push docker.io/adamoccidevops/vabucherback:${{ github.sha }}
        docker push docker.io/adamoccidevops/vabucherfront:${{ github.sha }}
        

